public void test04() throws Throwable  {
    long val1 = 9223372036854775807L;
    int val2 = -2;
    try {
        FieldUtils.safeMultiply(val1, val2);
        fail("Expected an ArithmeticException.");
    } catch (ArithmeticException ae) {
        assertEquals("Multiplication overflows a long: 9223372036854775807 * -2", ae.getMessage());
    }
}